spring:
  application:
    name: sistema-conciliacion-ucmc
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:conciliacion_db}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    co.edu.universidadmayor.conciliacion: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

app:
  pdf:
    output-directory: ${PDF_OUTPUT_DIR:./pdfs}
    university:
      name: "Universidad Colegio Mayor de Cundinamarca"
      center: "CENTRO DE CONCILIACIÓN"
      resolution: "Resolución No. 2099 de diciembre 12 de 2003"
      address: "Diagonal 34 No. 5-71 Teléfono 2457169 Bogotá, D.C."
      email: "conciliacion@universidadmayor.edu.co"
      code: "MPMFO-04 Versión 2"
      service-type: "Servicio Gratuito"